server:
  port: 9001
#数据库相关配置:
spring:
  datasource:
    username: root
    password: 6222688
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imagesproject?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
  #解析resources/静态资源
  mvc:
    static-path-pattern: /**
#默认的文件上传支持开启
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 2048MB

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log
fdfs:
  thumb-image:
    width: 60
    height: 60
  connect-timeout: 1500
  tracker-list:
    - 47.95.7.231:22122
  so-timeout: 1700